version: "2"

services:
  proxy:
    image: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  nexus:
    build: ./nexus

  sonar:
    build: ./sonar
    depends_on:
      - sonardb
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
  sonardb:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /opt/postgres/data:/var/lib/postgresql/data

  jenkins:
    build: ./jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /opt/jenkins/:/var/lib/jenkins/
    depends_on:
      - nexus
      - sonar
    environment:
      - NEXUS_PORT=8081
      - SONAR_PORT=9000
      - SONAR_DB_PORT=5432

  rundeck:
    image: jordan/rundeck
    volumes:
      - /opt/rundeck/etc/:/etc/rundeck
      - /opt/rundeck/log/:/var/log/rundeck
      - /opt/rundeck/plugin:/opt/rundeck-plugins
      - /opt/rundeck/storage:/var/lib/rundeck/var/storage
      - /opt/rundeck/mysql:/var/lib/mysql
    environment:
      - EXTERNAL_SERVER_URL=http://rundeck.sf.lan
